// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ0P8e3ftC_tWaEqG216nmj5-NPtOn50c',
    appId: '1:761274145264:web:f4705c4ee9c553c7222535',
    messagingSenderId: '761274145264',
    projectId: 'transport-management-dac5a',
    authDomain: 'transport-management-dac5a.firebaseapp.com',
    storageBucket: 'transport-management-dac5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPT6QkEjrd7srZ77cvWfbzD3T0kYhAP1s',
    appId: '1:761274145264:android:ec8e31160edf71b2222535',
    messagingSenderId: '761274145264',
    projectId: 'transport-management-dac5a',
    storageBucket: 'transport-management-dac5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWzSIzlGP9KB9aD0aRyGqb60H8LSLDJGE',
    appId: '1:761274145264:ios:f2a382703fd37610222535',
    messagingSenderId: '761274145264',
    projectId: 'transport-management-dac5a',
    storageBucket: 'transport-management-dac5a.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWzSIzlGP9KB9aD0aRyGqb60H8LSLDJGE',
    appId: '1:761274145264:ios:f2a382703fd37610222535',
    messagingSenderId: '761274145264',
    projectId: 'transport-management-dac5a',
    storageBucket: 'transport-management-dac5a.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ0P8e3ftC_tWaEqG216nmj5-NPtOn50c',
    appId: '1:761274145264:web:7eab92245cda8291222535',
    messagingSenderId: '761274145264',
    projectId: 'transport-management-dac5a',
    authDomain: 'transport-management-dac5a.firebaseapp.com',
    storageBucket: 'transport-management-dac5a.firebasestorage.app',
  );
}
