name: chauffeur_app
description: Transport Management System - Driver App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_database: ^11.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  geolocator_android: ^4.6.2
  permission_handler: ^11.3.1
  intl: ^0.19.0
  http: ^1.2.0
  flutter_map_tile_caching: ^10.0.0
  wakelock_plus: ^1.2.8
  flutter_compass: ^0.8.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/massar_logo.png"
  web:
    generate: true
    image_path: "assets/images/massar_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/massar_logo_splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#FFFFFF"
    image: assets/images/massar_logo_splash_android12.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/